# Generated by Django 4.0.3 on 2022-05-04 10:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colearning', '0004_spacecategory_alter_post_author_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='space',
            name='category',
        ),
        migrations.RemoveField(
            model_name='space',
            name='description',
        ),
        migrations.RemoveField(
            model_name='space',
            name='space_name',
        ),
        migrations.AddField(
            model_name='space',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='desription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='SpaceCategory',
        ),
    ]
