version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devuser
      - DB_USER=devuser
      - DB_PASS=changeme
    ports:
      - 8000:8000


    volumes:
      - ./app:/app
