# Generated by Django 4.0.3 on 2022-05-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_image_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='space',
        ),
        migrations.AddField(
            model_name='post',
            name='spaces',
            field=models.ManyToManyField(to='blog.space'),
        ),
        migrations.AlterField(
            model_name='space',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
