# Generated by Django 4.0.3 on 2022-05-09 19:28

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_space_post_spaces_alter_space_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='space',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='space',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
