# Generated by Django 4.0.3 on 2022-05-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_remove_space_title_post_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
    ]
