# Generated by Django 4.0.3 on 2022-05-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='spaces',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
