# Generated by Django 4.0.3 on 2022-05-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_spaces_delete_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
