# Generated by Django 4.0.3 on 2022-05-18 18:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='submitassignment',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
