# Generated by Django 4.0.3 on 2022-05-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_name', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Space Categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('interested_categories', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='space',
            name='content',
        ),
        migrations.RemoveField(
            model_name='space',
            name='title',
        ),
        migrations.AddField(
            model_name='space',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='space_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.user'),
        ),
        migrations.AddField(
            model_name='space',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db.spacecategory'),
        ),
    ]
